"""
Shared utilities for selfmanaged E2E tests (Flyte 2 "function" style).

Cloud-agnostic pieces live here: base dataclasses, the shared ``env`` used for
cloud-agnostic tasks, the bootstrap env for local-to-remote credential
plumbing, and all the @flyte.trace helpers that wrap uctl / helm / kubectl /
control-plane calls. Cloud-specific scripts (selfmanaged_aws_e2e.py,
selfmanaged_gcp_e2e.py) contribute their own TaskEnvironment with the cloud
CLIs layered onto ``base_image()``.
"""

from __future__ import annotations

import asyncio
import base64
import json
import logging
import os
import tempfile
import time
from dataclasses import dataclass, field

import flyte
from flyte.remote import Project, Secret
from flyteplugins.union.remote import ApiKey, Cluster

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)-7s %(name)s - %(message)s",
)
logger = logging.getLogger("flyte.e2e")


def say(msg: str) -> None:
    """Visible progress marker. Goes to stdout, bypasses the Flyte log
    router so it shows up in ``flyte run --local`` output even when the user
    has redirected stdout to a file."""
    print(f"[e2e] {msg}", flush=True)
    logger.info(msg)

# ============================================================================
# Tool versions (pinned)
# ============================================================================

_HELM_VERSION = "3.17.3"
_KUBECTL_VERSION = "1.31.4"
_YQ_VERSION = "4.45.4"
_UCTL_VERSION = "0.1.20"

# Bootstrap credential plumbing: one Flyte Secret holds the base64-encoded JSON
# {AKID, SAK, TOK, UAK}; the SDK injects it as ``_E2E_CREDS_B64`` into the
# remote task container. Local runs don't resolve secrets; we fall back to the
# ambient shell env.
E2E_CREDS_SECRET_KEY = "e2e_creds_b64"
E2E_CREDS_ENV_VAR = "_E2E_CREDS_B64"


# ============================================================================
# Dataclasses
# ============================================================================


@dataclass
class BaseConfig:
    """Cloud-agnostic knobs. Subclassed by AWSConfig / GCPConfig."""

    control_plane_url: str = ""
    cluster_name: str = ""

    helm_namespace: str = "union"
    helm_release_name: str = "union"
    helm_chart_repo: str = "https://github.com/unionai/helm-charts.git"
    # Empty = use the published unionai/dataplane chart from the repo.
    # Override via --helm_chart_branch if you want to test a WIP branch.
    helm_chart_branch: str = ""
    helm_chart_path: str = "charts/dataplane"
    helm_values_override: str = ""  # extra values file (e.g. "values-legacy.yaml" from the chart)
    dataplane_image_sha: str = ""  # if set, passed as --set image.union.tag=<sha>

    cluster_healthy_timeout: int = 300
    validate_timeout: int = 300

    skip_teardown: bool = False

    # Project to route test executions through. Defaults to cluster_name.
    test_project: str = ""

    def __post_init__(self):
        if not self.test_project:
            self.test_project = self.cluster_name


@dataclass(frozen=True)
class DataplaneValues:
    """Output of the ``provision_dataplane`` step."""

    yaml_text: str   # YAML generated by `uctl selfserve provision-dataplane-resources`
    org_name: str    # parsed from the same uctl output table


@dataclass(frozen=True)
class HelmRelease:
    name: str
    namespace: str


@dataclass
class TestResult:
    name: str
    passed: bool = False
    error: str = ""


@dataclass
class E2EResult:
    overall: str = ""  # "PASSED" | "FAILED"
    error: str = ""
    example_run_name: str = ""
    teardown_result: str = ""
    test_results: list[TestResult] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.overall == "PASSED"

    def summary(self) -> str:
        lines = [f"E2E Result: {self.overall}"]
        if self.error:
            lines.append(f"  Error: {self.error}")
        if self.example_run_name:
            lines.append(f"  Example run: {self.example_run_name}")
        if self.test_results:
            passed = sum(1 for t in self.test_results if t.passed)
            lines.append(f"  Verification: {passed}/{len(self.test_results)} passed")
            for t in self.test_results:
                status = "PASSED" if t.passed else "FAILED"
                line = f"    {t.name:<40} {status}"
                if t.error:
                    line += f"  {t.error[:80]}"
                lines.append(line)
        if self.teardown_result:
            lines.append(f"  Teardown: {self.teardown_result}")
        return "\n".join(lines)


# ============================================================================
# Base image (cloud-agnostic tooling). Cloud scripts extend with .with_commands()
# ============================================================================


def base_image() -> flyte.Image:
    """Debian + helm + kubectl + yq + uctl + uv + flyte/flyteplugins-union."""
    return (
        flyte.Image.from_debian_base()
        .with_apt_packages(
            "curl", "ca-certificates", "git", "jq", "unzip", "gnupg", "lsb-release",
        )
        .with_pip_packages("flyte", "flyteplugins-union", "keyring", "fastapi")
        .with_commands([
            # Helm
            f"curl -fsSL https://get.helm.sh/helm-v{_HELM_VERSION}-linux-amd64.tar.gz"
            f" | tar xz -C /tmp && mv /tmp/linux-amd64/helm /usr/local/bin/ && rm -rf /tmp/linux-amd64",
            # kubectl
            f"curl -fsSLo /usr/local/bin/kubectl"
            f" https://dl.k8s.io/release/v{_KUBECTL_VERSION}/bin/linux/amd64/kubectl"
            f" && chmod +x /usr/local/bin/kubectl",
            # yq
            f"curl -fsSLo /usr/local/bin/yq"
            f" https://github.com/mikefarah/yq/releases/download/v{_YQ_VERSION}/yq_linux_amd64"
            f" && chmod +x /usr/local/bin/yq",
            # uctl
            f"curl -fsSL https://github.com/unionai/uctl/releases/download/v{_UCTL_VERSION}/uctl_Linux_x86_64.tar.gz"
            f" | tar xz -C /usr/local/bin uctl",
            # uv (for the flyte CLI's in-image venvs during validation)
            "curl -fsSL https://astral.sh/uv/install.sh | sh"
            " && mv /root/.local/bin/uv /usr/local/bin/",
        ])
    )


# ============================================================================
# Shell — the one primitive that actually runs commands. Async so the event
# loop stays free; traced so every invocation becomes a checkpoint that won't
# re-run on task retry once it succeeds.
# ============================================================================


@flyte.trace
async def sh(cmd: str, *, check: bool = True) -> str:
    """Run a shell command. Always captures and returns stdout as a string.

    stdout and stderr are logged live so callers that don't use the return
    value still get visible progress. Pass ``check=False`` to tolerate a
    non-zero exit code (returns stdout regardless; errors go to the log).
    """
    logger.info(f"  $ {cmd}")
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out_b, err_b = await proc.communicate()
    out = (out_b or b"").decode(errors="replace")
    err = (err_b or b"").decode(errors="replace")
    if out.strip():
        logger.info(out.rstrip())
    if err.strip():
        logger.warning(err.rstrip())
    if check and proc.returncode != 0:
        raise RuntimeError(f"Command failed (exit {proc.returncode}): {cmd}\n{err}")
    return out


@flyte.trace
async def sh_ok(cmd: str) -> bool:
    """True iff the command succeeds. Never raises."""
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
    )
    await proc.communicate()
    return proc.returncode == 0


# ============================================================================
# Bootstrap — move local credentials into a Flyte Secret for the remote path.
# ============================================================================

bootstrap_env = flyte.TaskEnvironment(name="selfmanaged-bootstrap")


def _read_local_credentials() -> dict[str, str]:
    """Read AWS STS creds + UNION_API_KEY from the local shell."""
    creds = {
        "AKID": os.environ.get("AWS_ACCESS_KEY_ID", ""),
        "SAK":  os.environ.get("AWS_SECRET_ACCESS_KEY", ""),
        "TOK":  os.environ.get("AWS_SESSION_TOKEN", ""),
        "UAK":  os.environ.get("UNION_API_KEY", ""),
    }
    missing = [k for k in ("AKID", "SAK") if not creds[k]]
    if missing:
        raise RuntimeError(
            f"Missing AWS credentials in env: {missing}. "
            "Export AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY first."
        )
    return creds


@bootstrap_env.task
async def stash_credentials() -> str:
    """Stash AWS + Union creds from the local shell into a Flyte Secret.

    Run once per shell session (creds rotate with STS tokens). The remote
    ``main`` reads the secret via the env's ``secrets=`` declaration; no creds
    pass through task arguments.
    """
    creds = _read_local_credentials()
    blob = base64.b64encode(json.dumps(creds).encode()).decode()
    flyte.init_from_config()
    Secret.create(name=E2E_CREDS_SECRET_KEY, value=blob, type="regular")
    logger.info(
        f"Secret '{E2E_CREDS_SECRET_KEY}' created ({len(blob)} chars). "
        f"Remote tasks will see it as env var ${E2E_CREDS_ENV_VAR}."
    )
    return E2E_CREDS_SECRET_KEY


async def init_union_client(cfg: "BaseConfig", org: str = "") -> None:
    """Initialize the flyte / flyteplugins-union control-plane client.

    Required before calling ``Cluster.get``, ``ApiKey.create``,
    ``Project.create``, or ``flyte.run.aio`` — they all call
    ``ensure_client()`` under the hood and raise InitializationError if
    nothing has set up the client yet. The SDK's SelectCluster RPC (used for
    code-bundle uploads) also needs ``org`` to route correctly; pass it
    once you know it.

    Always pins endpoint explicitly (ignores ~/.flyte/config.yaml). With
    ``UNION_API_KEY`` set we authenticate via api key; otherwise default
    PKCE pulls a cached token from the keyring.

    Uses the ``.aio`` variants because the sync wrappers raise
    "Deadlock detected" when invoked from an async task. Idempotent.
    """
    api_key = os.environ.get("UNION_API_KEY", os.environ.get("FLYTE_API_KEY", ""))
    kwargs: dict = {
        "endpoint": cfg.control_plane_url,
        "project": cfg.test_project,
        "domain": "development",
    }
    if org:
        kwargs["org"] = org
    if api_key:
        kwargs["api_key"] = api_key
    await flyte.init.aio(**kwargs)


async def hydrate_credentials() -> None:
    """Populate AWS + UNION env vars from the bootstrap secret, if needed.

    Call this at the top of any task that shells out to aws/gcloud/uctl.
    - Local run: ambient AWS_ACCESS_KEY_ID already set → no-op.
    - Remote run: the SDK has injected ``_E2E_CREDS_B64``; decode and export.

    Deliberately not a ``@flyte.trace``: hydrating is idempotent env-var
    manipulation with no return value — memoization would only serve to
    persist credential material in the trace store.
    """
    if os.environ.get("AWS_ACCESS_KEY_ID"):
        return
    blob = os.environ.get(E2E_CREDS_ENV_VAR)
    if not blob:
        raise RuntimeError(
            f"No AWS credentials: neither ambient env nor {E2E_CREDS_SECRET_KEY!r} "
            f"secret ({E2E_CREDS_ENV_VAR}). Run `flyte run --local "
            f"selfmanaged_common.py stash_credentials` first."
        )
    creds = json.loads(base64.b64decode(blob))
    os.environ["AWS_ACCESS_KEY_ID"] = creds["AKID"]
    os.environ["AWS_SECRET_ACCESS_KEY"] = creds["SAK"]
    if creds.get("TOK"):
        os.environ["AWS_SESSION_TOKEN"] = creds["TOK"]
    if creds.get("UAK"):
        os.environ["UNION_API_KEY"] = creds["UAK"]


# ============================================================================
# Phase 1 — Dataplane provisioning (uctl; shell out because no Python API yet)
# ============================================================================


@flyte.trace
async def provision_dataplane(cfg: BaseConfig, provider: str) -> DataplaneValues:
    """Run `uctl selfserve provision-dataplane-resources`.

    Returns the generated YAML text and the parsed org name. The YAML is not
    written anywhere persistent; callers materialize it to a temp file before
    passing to helm.
    """
    assert cfg.control_plane_url, "control_plane_url is required"
    assert cfg.cluster_name, "cluster_name is required"

    work_dir = tempfile.mkdtemp(prefix="union-e2e-provision-")
    say(f"provision_dataplane: running uctl selfserve on {cfg.control_plane_url} "
        f"(cluster={cfg.cluster_name}, provider={provider})")

    # ``hydrate_credentials`` has already populated UNION_API_KEY (either from
    # the ambient shell or the injected secret), so uctl config init runs
    # non-interactively and does not need a TTY.
    await sh(f"cd {work_dir} && uctl config init --host={cfg.control_plane_url}")
    output = await sh(
        f"cd {work_dir} && "
        f"uctl selfserve provision-dataplane-resources "
        f"--clusterName {cfg.cluster_name} --provider {provider}"
    )

    # Find the generated values file in the temp dir.
    values_file = ""
    for line in output.splitlines():
        if "Generated" in line and ".yaml" in line:
            for word in line.split():
                if word.endswith(".yaml"):
                    values_file = os.path.join(work_dir, word)
                    break
            if values_file:
                break
    if not values_file or not os.path.exists(values_file):
        import glob
        candidates = glob.glob(os.path.join(work_dir, "*-values.yaml"))
        if candidates:
            values_file = candidates[0]
    if not values_file or not os.path.exists(values_file):
        raise RuntimeError(
            f"Could not find generated values file in {work_dir}. uctl output:\n{output}"
        )

    with open(values_file) as f:
        yaml_text = f.read()
    say(f"provision_dataplane: got values YAML ({len(yaml_text)} chars) from {values_file}")

    # Parse org name from the uctl output table (first table row matching
    # cluster_name contains [_, org, ...] between pipes).
    org_name = ""
    for line in output.splitlines():
        if cfg.cluster_name in line and "|" in line:
            fields = [f.strip() for f in line.split("|")]
            if len(fields) >= 3 and fields[1]:
                org_name = fields[1]
                break
    if org_name:
        say(f"provision_dataplane: org={org_name}")

    return DataplaneValues(yaml_text=yaml_text, org_name=org_name)


# ============================================================================
# Phase 2 — Helm chart management
# ============================================================================


@flyte.trace
async def resolve_chart_ref(cfg: BaseConfig) -> str:
    """Return a chart ref for helm (local path from git branch, or repo alias)."""
    if cfg.helm_chart_branch:
        say(f"resolve_chart_ref: cloning {cfg.helm_chart_repo}@{cfg.helm_chart_branch}")
        clone_dir = tempfile.mkdtemp(prefix="union-e2e-helm-")
        await sh(
            f"git clone --depth 1 --branch {cfg.helm_chart_branch} "
            f"{cfg.helm_chart_repo} {clone_dir}"
        )
        chart_ref = f"{clone_dir}/{cfg.helm_chart_path}"
        await sh(f"helm dependency update {chart_ref}", check=False)
        say(f"resolve_chart_ref: using local chart at {chart_ref}")
        return chart_ref
    say("resolve_chart_ref: using published unionai/dataplane")
    await sh(
        "helm repo add unionai https://unionai.github.io/helm-charts/ --force-update",
        check=False,
    )
    # Only refresh the unionai repo — `helm repo update` (no args) fails if
    # any unrelated repo on the local helm config is unreachable.
    await sh("helm repo update unionai")
    return "unionai/dataplane"


async def _watch_pods(namespace: str, stop: asyncio.Event, interval: int = 15) -> None:
    """Periodically dump `kubectl get pods -A` to the log until stopped.

    Untraced on purpose — this is diagnostic polling; each tick as a trace
    record would bloat the action store for no benefit.
    """
    while not stop.is_set():
        try:
            proc = await asyncio.create_subprocess_shell(
                "kubectl get pods -A --field-selector=metadata.namespace!=kube-system",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            out, _ = await proc.communicate()
            text = (out or b"").decode(errors="replace").rstrip()
            if text:
                say("[pods] ↓\n" + text)
        except Exception as e:
            say(f"[pods] watcher error: {e}")
        try:
            await asyncio.wait_for(stop.wait(), timeout=interval)
        except asyncio.TimeoutError:
            pass


@flyte.trace
async def helm_install(cfg: BaseConfig, values_yaml: str, chart_ref: str) -> HelmRelease:
    """Materialize values YAML to a temp file and `helm upgrade --install`."""
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False, prefix="union-e2e-values-",
    )
    tmp.write(values_yaml)
    tmp.close()
    values_file = tmp.name
    say(f"helm_install: values file at {values_file}, chart_ref={chart_ref}")

    override_flag = ""
    if cfg.helm_values_override:
        override_path = cfg.helm_values_override
        if not os.path.isabs(override_path) and "/" not in override_path and os.path.isdir(chart_ref):
            candidate = os.path.join(chart_ref, override_path)
            if os.path.exists(candidate):
                override_path = candidate
        override_flag = f'-f "{override_path}" '
        logger.info(f"  Using values override: {override_path}")

    image_tag_flag = ""
    if cfg.dataplane_image_sha:
        image_tag_flag = f"--set image.union.tag={cfg.dataplane_image_sha} "
        logger.info(f"  Overriding dataplane image tag: {cfg.dataplane_image_sha}")

    # ``--take-ownership`` (Helm 3.17+) lets an install/upgrade adopt existing
    # cluster resources (CRDs, namespaces) that lack Helm's owner annotations.
    # Without it, reruns after a partial install fail with "invalid ownership
    # metadata" on things like the knative-operator CRDs.
    say(f"helm_install: running `helm upgrade --install {cfg.helm_release_name}` "
        f"(this may take several minutes while --wait blocks on ready pods)...")

    stop = asyncio.Event()
    watcher = asyncio.create_task(_watch_pods(cfg.helm_namespace, stop))
    try:
        await sh(
            f"helm upgrade --install {cfg.helm_release_name} {chart_ref} "
            f"{override_flag}{image_tag_flag}-f \"{values_file}\" "
            f"-n {cfg.helm_namespace} --create-namespace --wait --timeout 10m "
            f"--force-conflicts --take-ownership"
        )
    finally:
        stop.set()
        try:
            await asyncio.wait_for(watcher, timeout=5)
        except asyncio.TimeoutError:
            watcher.cancel()

    say(f"helm_install: installed release '{cfg.helm_release_name}' in ns '{cfg.helm_namespace}'")
    return HelmRelease(name=cfg.helm_release_name, namespace=cfg.helm_namespace)


@flyte.trace
async def helm_uninstall(cfg: BaseConfig) -> list[str]:
    """Uninstall the release if it exists. Returns list of error messages."""
    errors: list[str] = []
    if await sh_ok(f"helm status {cfg.helm_release_name} -n {cfg.helm_namespace}"):
        logger.info(f"Uninstalling Helm release {cfg.helm_release_name}...")
        if not await sh_ok(
            f"helm uninstall {cfg.helm_release_name} -n {cfg.helm_namespace} "
            f"--wait --timeout 5m"
        ):
            errors.append("Helm uninstall failed")
    return errors


# ============================================================================
# Phase 3 — Cluster pool / project / routing (control plane calls)
# ============================================================================


@flyte.trace
async def create_eager_api_key(cfg: BaseConfig) -> None:
    """Create the EAGER_API_KEY used by eager mode. Idempotent."""
    await init_union_client(cfg)
    try:
        await ApiKey.create.aio(name="EAGER_API_KEY")
        logger.info("EAGER_API_KEY created.")
    except Exception as e:
        # No typed AlreadyExists in the current SDK; re-creation surfaces as
        # a raw error. Safe to treat as pre-existing on reruns.
        logger.info(f"EAGER_API_KEY not created (likely exists): {e}")


@flyte.trace
async def create_cluster_pool(cfg: BaseConfig, org_name: str, pool_name: str) -> None:
    """`uctl create clusterpool` (no Python API yet in flyteplugins-union)."""
    org_flag = f"--org {org_name}" if org_name else ""
    spec = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False, prefix="clusterpool-",
    )
    spec.write(f"clusterPool:\n  id:\n    name: {pool_name}\n")
    spec.close()
    try:
        await sh(
            f"uctl create clusterpool --clusterPoolSpecFile {spec.name} {org_flag}",
            check=False,
        )
    finally:
        os.unlink(spec.name)
    logger.info(f"Cluster pool '{pool_name}' created/verified.")


@flyte.trace
async def assign_cluster_to_pool(
    cfg: BaseConfig, org_name: str, pool_name: str
) -> None:
    """`uctl create clusterpoolassignment`. Idempotent via check=False."""
    org_flag = f"--org {org_name}" if org_name else ""
    await sh(
        f"uctl create clusterpoolassignment "
        f"--poolName {pool_name} --clusterName {cfg.cluster_name} {org_flag}",
        check=False,
    )
    logger.info(f"Cluster '{cfg.cluster_name}' assigned to pool '{pool_name}'.")


@flyte.trace
async def create_project(cfg: BaseConfig) -> str:
    """`flyte.remote.Project.create`. Idempotent — swallow AlreadyExists."""
    await init_union_client(cfg)
    try:
        await Project.create.aio(
            id=cfg.test_project,
            name=cfg.test_project,
            description=f"E2E test project for cluster {cfg.cluster_name}",
        )
        logger.info(f"Project '{cfg.test_project}' created.")
    except Exception as e:
        logger.info(f"Project '{cfg.test_project}' not created (likely exists): {e}")
    return cfg.test_project


@flyte.trace
async def route_project_to_pool(
    cfg: BaseConfig, org_name: str, pool_name: str, domain: str
) -> None:
    """`uctl --logger.level 6 update cluster-pool-attributes` for one (project, domain, pool)."""
    org_flag = f"--org {org_name}" if org_name else ""
    attr = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False, prefix=f"cpa-{domain}-",
    )
    attr.write(
        f"domain: {domain}\n"
        f"project: {cfg.test_project}\n"
        f"clusterPoolName: {pool_name}\n"
    )
    attr.close()
    try:
        say(f"uctl update cluster-pool-attributes --force --attrFile {attr.name} {org_flag}")
        say(f"org: {org_name}\n"        
            f"domain: {domain}\n"
                    f"project: {cfg.test_project}\n"
                    f"clusterPoolName: {pool_name}\n"
                    )
        await sh(
            f"uctl update cluster-pool-attributes --force --attrFile {attr.name} {org_flag}",
            check=False,
        )
    finally:
        os.unlink(attr.name)


@flyte.trace
async def create_test_project_and_route(cfg: BaseConfig, org_name: str) -> str:
    """End-to-end: pool + assignment + project + per-domain routing.

    Returns the project name on success.
    """
    pool_name = cfg.cluster_name
    say(f"create_test_project_and_route: pool={pool_name} project={cfg.test_project} org={org_name}")
    await create_cluster_pool(cfg, org_name, pool_name)
    await assign_cluster_to_pool(cfg, org_name, pool_name)
    project = await create_project(cfg)
    for domain in ("development", "staging", "production"):
        await route_project_to_pool(cfg, org_name, pool_name, domain)
    say(f"create_test_project_and_route: project '{project}' routed to pool '{pool_name}' (dev/staging/prod)")
    return project


# ============================================================================
# Phase 4 — Health check
# ============================================================================


@flyte.trace
async def cluster_wait_healthy(cfg: BaseConfig) -> str:
    """Poll until cluster is enabled + healthy. Returns the cluster's org name.

    Plain ``asyncio.sleep`` is correct here: a @flyte.trace memoizes its
    successful return, so a retry of the enclosing task replays this result
    without re-polling.
    """
    await init_union_client(cfg)
    say(f"cluster_wait_healthy: polling Cluster.get(name={cfg.cluster_name}) "
        f"(timeout {cfg.cluster_healthy_timeout}s)")
    deadline = time.time() + cfg.cluster_healthy_timeout
    while time.time() < deadline:
        try:
            cluster = await Cluster.get.aio(name=cfg.cluster_name)
        except Exception as e:
            say(f"cluster_wait_healthy: Cluster.get failed ({e}); retrying in 15s")
            await asyncio.sleep(15)
            continue
        if cluster.state == "enabled" and cluster.health == "healthy":
            say(f"cluster_wait_healthy: {cfg.cluster_name} is enabled+healthy (org={cluster.organization})")
            return cluster.organization or ""
        say(f"cluster_wait_healthy: state={cluster.state} health={cluster.health}, waiting 15s")
        await asyncio.sleep(15)
    raise RuntimeError(
        f"Cluster {cfg.cluster_name} did not become healthy within "
        f"{cfg.cluster_healthy_timeout}s"
    )


@flyte.trace
async def detect_org_name(cfg: BaseConfig) -> str:
    """Best-effort org lookup via Cluster.get. Returns "" on failure."""
    await init_union_client(cfg)
    try:
        cluster = await Cluster.get.aio(name=cfg.cluster_name)
        return cluster.organization or ""
    except Exception as e:
        logger.info(f"  Cluster.get failed in detect_org_name: {e}")
        return ""


# ============================================================================
# Phase 4 — Smoke test (hello workflow)
# ============================================================================



# ============================================================================
# Debug collection (best-effort on failure)
# ============================================================================


@flyte.trace
async def collect_debug_dumps(cfg: BaseConfig, debug_dir: str) -> str:
    """Dump cluster state to ``debug_dir`` for failure post-mortems."""
    if not await sh_ok("kubectl cluster-info"):
        logger.warning("No cluster access — skipping debug dump.")
        return debug_dir

    os.makedirs(debug_dir, exist_ok=True)
    logger.info(f"Collecting debug dumps to {debug_dir}...")

    async def _dump(cmd: str, path: str) -> None:
        proc = await asyncio.create_subprocess_shell(
            cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        out, err = await proc.communicate()
        with open(path, "wb") as f:
            f.write(out or b"")
            if err:
                f.write(b"\n--- stderr ---\n")
                f.write(err)
        if os.path.getsize(path) == 0:
            os.remove(path)

    await asyncio.gather(
        _dump("kubectl get pods -A -o wide", f"{debug_dir}/pods-all.txt"),
        _dump(
            "kubectl get events -A --sort-by='.lastTimestamp'",
            f"{debug_dir}/events.txt",
        ),
        _dump("kubectl get nodes -o wide", f"{debug_dir}/nodes.txt"),
        _dump(
            f"helm status {cfg.helm_release_name} -n {cfg.helm_namespace}",
            f"{debug_dir}/helm-status.txt",
        ),
    )

    pod_logs_dir = f"{debug_dir}/pod-logs"
    os.makedirs(pod_logs_dir, exist_ok=True)
    pods_output = await sh("kubectl get pods -A --no-headers", check=False)
    for line in pods_output.strip().splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        ns, pod, _, status = parts[0], parts[1], parts[2], parts[3]
        if status in ("Running", "Succeeded", "Completed"):
            continue
        pod_dir = f"{pod_logs_dir}/{ns}--{pod}"
        os.makedirs(pod_dir, exist_ok=True)
        await _dump(f"kubectl describe pod {pod} -n {ns}", f"{pod_dir}/describe.txt")
        containers = await sh(
            f"kubectl get pod {pod} -n {ns} -o jsonpath='{{.spec.containers[*].name}}'",
            check=False,
        )
        for container in containers.split():
            await _dump(
                f"kubectl logs {pod} -n {ns} -c {container}",
                f"{pod_dir}/{container}.log",
            )
            await _dump(
                f"kubectl logs {pod} -n {ns} -c {container} --previous",
                f"{pod_dir}/{container}.previous.log",
            )

    logger.info(f"Debug dumps written to {debug_dir}")
    return debug_dir
