name: Build and deploy unionai-docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Optional VERSION env for Makefile (e.g. 1.2.3)"
        required: false
        type: string
  push:
    branches:
      - "worker/**"

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}   # passed into Makefile if provided
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Ensure scripts are executable
        run: chmod +x scripts/*.sh tools/*/*/*.sh || true

      - name: Build via Makefile
        run: make dist

      - name: Debug - Check build output
        run: |
          echo "Checking dist directory structure:"
          ls -la dist/
          echo "Checking wrangler.jsonc:"
          cat wrangler.jsonc

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy