name: Check Generated Content

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-generated-content:
    name: "Check Generated Content"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0

      - name: Check generated content exists
        run: make check-generated-content
