name: Check Jupyter Notebooks

on:
  pull_request:
  push:
    branches: [v1]

jobs:
  check-jupyter:
    name: "Check Jupyter Notebooks"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Validate notebook hashes
        run: make check-jupyter

      - name: Report status
        if: ${{ failure() }}
        run: |
          echo "::error::Jupyter notebook validation failed. Run 'make -f Makefile.jupyter' locally to regenerate."
